#FROM eclipse-temurin:11-jdk-alpine
FROM arm64v8/eclipse-temurin:11-jdk

EXPOSE 8081

RUN mkdir -p /opt/ucb-judge/logs/uj-email
VOLUME /opt/ucb-judge/logs/uj-mail

VOLUME /tmp

ENV CONFIG_SERVER_URI="CONFIG_SERVER_URI"

ENV EUREKA_SERVER_URI="EUREKA_SERVER_URI"
ENV CONFIG_SERVER_PROFILE="CONFIG_SERVER_PROFILE"
ENV ZIPKIN_SERVER_URI="ZIPKIN_SERVER_URI"

ENV RABBITMQ_HOST="RABBITMQ_HOST"
ENV RABBITMQ_USERNAME="RABBITMQ_USERNAME"
ENV RABBITMQ_PASSWORD="RABBITMQ_PASSWORD"
ENV RABBITMQ_VIRTUAL_HOST="RABBITMQ_VIRTUAL_HOST"

ENV EMAIL_HOST="EMAIL_HOST"
ENV EMAIL_USERNAME="EMAIL_USERNAME"
ENV EMAIL_PASSWORD="EMAIL_PASSWORD"

ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-cp","app:app/lib/*","ucb.judge.ujemail.UjEmailApplicationKt"]
